### ISSUE TITLE
Discussion to change the polyfill approach

### ISSUE THREAD

**Issue by lucasfeliciano** [lucasfeliciano/fetch-everywhere#5]
I'm tending to make the polyfill optional.

The Idea is to use like:

``` js
import fetch from 'fetch-everywhere';
```

This will check the environment and depending on the environment it will export one of these:
- For browser: https://github.com/github/fetch
- For node: https://github.com/bitinn/node-fetch
- If the environment have `fetch` defined in the global scope (the case of react-native), it will just export a reference to it.

Also we have a option to apply the polyfill:

``` js
require('fetch-everywhere').polyfill()
```

Doing that we will apply fetch to the global scope.

**Comment by montogeek** [comment]
At this moment i am using it like `import 'fetch-everywhere'` because these reasons https://github.com/wheresrhys/fetch-mock#fetch-is-assigned-to-a-local-variable-not-a-global

**Comment by lucasfeliciano** [comment]
@montogeek 

In this case you will do like this:

```
require('fetch-everywhere').polyfill();
```

I don't think it is a good practice mess with the global object, so if we could keep things in the local scope it is better.

For cases that you need to use in the global scope you can do it explicitly calling the `polyfill()` method
