### ISSUE TITLE
This still does not build with webpack - "TypeError: Cannot read property 'bind' of undefined" when running mocha tests in command line as soon as I attempt to use fetch-everywhere

### ISSUE THREAD

**Issue by marktrobinson** [lucasfeliciano/fetch-everywhere#7]
```// the whatwg-fetch polyfill installs the fetch() function
// on the global object (window or self)
//
// Return that as the export for use in Webpack, Browserify etc.
__webpack_require__(86);
var globalObj = typeof self !== 'undefined' && self || this;
module.exports = globalObj.fetch.bind(globalObj);
```

TypeError: Cannot read property 'bind' of undefined

This still does not work when building with webpack2

I thought this is what fetch-everywhere was supposed to fix: https://github.com/matthew-andrews/isomorphic-fetch/issues/59

**Comment by marktrobinson** [comment]
So, if anyone has this problem in the future:

1. Use isomorphic-fetch or fetch-everywhere (I used isomorphic but this one will work as well)
2. when using webpack make sure your target is set to 'web'
3. `import 'isomorphic-fetch'` in your index.js or otherwise root file
4. import 'isomorphic-fetch' in your test files
5. your tests will now use node-fetch and your webpack will now build whatwg-fetch

**Comment by dreamcog** [comment]
@Guacaswole I have the same problem, just changed isomorphic-fetch into fetch-evertwhere.
have a error,when I use node to run it.
`module.exports = globalObj.fetch.bind(globalObj);
                                ^
TypeError: Cannot read property 'bind' of undefined`

in your comment.you mentioned "when using webpack make sure your target is set to 'web'"
could you give some code to explain that?

thanks a lot

**Comment by dreamcog** [comment]
@Guacaswole I saw it in webpack document .
thanks anyway 

👍
