### ISSUE TITLE
React Native: undefined is not an object (evaluating 'n.fetch.bind')

### ISSUE THREAD

**Issue by bonustrack** [lucasfeliciano/fetch-everywhere#8]
I've decided to move from `isomorphic-fetch` to `fetch-everywhere` for solve the issue `Can't find variable: self` . But now i got another issue `undefined is not an object (evaluating 'n.fetch.bind')` 

![image](https://user-images.githubusercontent.com/16245250/29106782-1e4b52d2-7d01-11e7-97d4-f54c12be7892.png)

Any idea how to solve this?

**Comment by lucasfeliciano** [comment]
Can you give more information about your environment?

**Comment by bonustrack** [comment]
This is my environment when this error appear:
OS: OSX
IDE: WebStorm
`react@16.0.0-alpha.6`
`react-native@0.44.0`

I've finally switched to `fetch-ponyfill` feel free to close this issue.

**Comment by lucasfeliciano** [comment]
fetch-ponyfill is a good option too.

thanks for further information anyway :)

**Comment by pinchez254** [comment]
how do you handle the error that appears when there is nothing more to fetch

**Comment by pinchez254** [comment]
am getting object is null when i scroll to fetch more up to the point there is no more data to fetch.
